# Funding is currently disabled for this project.
# To enable, uncomment a platform and add your username:
#
# github: [sultanroot3-ux]
# ko_fi: your-username
# buy_me_a_coffee: your-username
# custom: ["https://example.com/donate"]
