#!/usr/bin/env bash
# SentinelAI — single-command production install for a fresh Ubuntu server.
#
#   sudo bash deployment/install_ubuntu.sh --domain sentinel.example.com --email admin@example.com
#
# What it does:
#   1. Installs Docker Engine + compose plugin (if missing)
#   2. Generates .env with strong random secrets (if missing)
#   3. Obtains a Let's Encrypt certificate for --domain (or generates a
#      self-signed one with --self-signed for LAN/IP-only deployments)
#   4. Renders the production nginx config
#   5. Builds and starts the full stack (db, backend, nginx, certbot, backups)
#   6. Smoke-tests /api/health and prints next steps
#
# Idempotent: safe to re-run; existing .env and certificates are kept.
set -euo pipefail

DOMAIN=""
EMAIL=""
SELF_SIGNED=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)      DOMAIN="$2"; shift 2 ;;
    --email)       EMAIL="$2"; shift 2 ;;
    --self-signed) SELF_SIGNED=1; shift ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ $SELF_SIGNED -eq 0 && ( -z "$DOMAIN" || -z "$EMAIL" ) ]]; then
  echo "Usage: sudo bash deployment/install_ubuntu.sh --domain <fqdn> --email <email>" >&2
  echo "       sudo bash deployment/install_ubuntu.sh --self-signed   (LAN / IP-only)" >&2
  exit 1
fi
[[ $SELF_SIGNED -eq 1 && -z "$DOMAIN" ]] && DOMAIN="_"

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
echo "==> SentinelAI installer — project root: $ROOT"

# ---------------------------------------------------------------- 1. Docker
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker Engine..."
  apt-get update
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
else
  echo "==> Docker already installed: $(docker --version)"
fi

# ---------------------------------------------------------------- 2. .env
if [[ ! -f .env ]]; then
  echo "==> Generating .env with random secrets"
  cat > .env <<EOF
# Generated by install_ubuntu.sh on $(date -u +%FT%TZ) — keep this file secret.
SENTINEL_SECRET_KEY=$(openssl rand -hex 32)
SENTINEL_DB_PASSWORD=$(openssl rand -hex 24)
DOMAIN=$DOMAIN
UVICORN_WORKERS=2
BACKUP_RETENTION_DAYS=14
EOF
  chmod 600 .env
else
  echo "==> Keeping existing .env"
  grep -q "^DOMAIN=" .env || echo "DOMAIN=$DOMAIN" >> .env
fi

# ---------------------------------------------------------------- 3. TLS cert
mkdir -p backups
if [[ $SELF_SIGNED -eq 1 ]]; then
  echo "==> Generating self-signed certificate (LAN mode)"
  docker volume create sentinelai_certbot-certs >/dev/null
  docker run --rm -v sentinelai_certbot-certs:/etc/letsencrypt alpine/openssl req -x509 \
    -newkey rsa:2048 -nodes -days 825 \
    -keyout "/etc/letsencrypt/live/$DOMAIN/privkey.pem" \
    -out "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" \
    -subj "/CN=sentinelai.local" 2>/dev/null || {
      # alpine/openssl lacks mkdir; do it in two steps
      docker run --rm -v sentinelai_certbot-certs:/etc/letsencrypt alpine \
        mkdir -p "/etc/letsencrypt/live/$DOMAIN"
      docker run --rm -v sentinelai_certbot-certs:/etc/letsencrypt alpine/openssl req -x509 \
        -newkey rsa:2048 -nodes -days 825 \
        -keyout "/etc/letsencrypt/live/$DOMAIN/privkey.pem" \
        -out "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" \
        -subj "/CN=sentinelai.local"
    }
else
  echo "==> Obtaining Let's Encrypt certificate for $DOMAIN"
  docker volume create sentinelai_certbot-certs >/dev/null
  docker volume create sentinelai_certbot-www >/dev/null
  if docker run --rm -v sentinelai_certbot-certs:/etc/letsencrypt alpine \
       test -e "/etc/letsencrypt/live/$DOMAIN/fullchain.pem"; then
    echo "    Certificate already present — skipping issuance"
  else
    # Standalone issuance requires port 80 to be free (stack not yet running)
    docker run --rm -p 80:80 \
      -v sentinelai_certbot-certs:/etc/letsencrypt \
      -v sentinelai_certbot-www:/var/www/certbot \
      certbot/certbot certonly --standalone --non-interactive --agree-tos \
      -m "$EMAIL" -d "$DOMAIN"
  fi
fi

# ---------------------------------------------------------------- 4. nginx conf
echo "==> Rendering nginx production config"
export DOMAIN
envsubst '${DOMAIN}' < docker/nginx.prod.conf.template > docker/nginx.rendered.conf

# ---------------------------------------------------------------- 5. stack up
echo "==> Building and starting the stack"
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

# ---------------------------------------------------------------- 6. smoke test
echo "==> Waiting for backend health..."
for i in $(seq 1 30); do
  if curl -fsS http://localhost/api/health >/dev/null 2>&1; then
    echo "==> Health check OK"
    break
  fi
  [[ $i -eq 30 ]] && { echo "ERROR: backend did not become healthy" >&2; exit 1; }
  sleep 2
done

cat <<EOF

============================================================
 SentinelAI is running.

   Dashboard:  https://$DOMAIN/
   Health:     http://$DOMAIN/api/health
   First login: admin / admin123  (you will be forced to
                change this password immediately)

 Ops quick reference:
   Status:     docker compose ps
   Logs:       docker compose logs -f backend
   Backups:    ls backups/   (daily, ${BACKUP_RETENTION_DAYS:-14}-day retention)
   Update:     git pull && docker compose -f docker-compose.yml \\
               -f docker-compose.prod.yml up -d --build
============================================================
EOF
