"""investigation system: rbac, cameras, embeddings, visitors, watchlists, access history

Revision ID: 09dfff37227f
Revises: adfe449d4708
Create Date: 2026-07-23 13:58:18.452003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dfff37227f'
down_revision: Union[str, Sequence[str], None] = 'adfe449d4708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('building', sa.String(length=120), nullable=True),
    sa.Column('floor', sa.String(length=40), nullable=True),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_camera_locations_id'), 'camera_locations', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['camera_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_table('access_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('unknown_face_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unknown_face_id'], ['unknown_faces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_history_id'), 'access_history', ['id'], unique=False)
    op.create_index(op.f('ix_access_history_timestamp'), 'access_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_access_history_unknown_face_id'), 'access_history', ['unknown_face_id'], unique=False)
    op.create_index(op.f('ix_access_history_user_id'), 'access_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_access_history_visitor_id'), 'access_history', ['visitor_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unknown_face_id', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('model', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unknown_face_id'], ['unknown_faces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_id'), 'face_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_unknown_face_id'), 'face_embeddings', ['unknown_face_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unknown_face_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unknown_face_id'], ['unknown_faces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_id'), 'watchlist_entries', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_unknown_face_id'), 'watchlist_entries', ['unknown_face_id'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_user_id'), 'watchlist_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_watchlist_entries_watchlist_id'), 'watchlist_entries', ['watchlist_id'], unique=False)
    op.add_column('recognition_logs', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_recognition_logs_camera_id', 'recognition_logs', 'cameras', ['camera_id'], ['id'], ondelete='SET NULL')
    op.add_column('unknown_faces', sa.Column('unknown_person_id', sa.String(length=20), nullable=True))
    op.add_column('unknown_faces', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_unknown_faces_unknown_person_id'), 'unknown_faces', ['unknown_person_id'], unique=True)
    op.create_foreign_key('fk_unknown_faces_camera_id', 'unknown_faces', 'cameras', ['camera_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('job_title', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('office_building', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('badge_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=40), nullable=True))
    # server_default so existing rows satisfy NOT NULL; matches ORM default
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False,
                                     server_default='active'))
    op.create_unique_constraint('uq_users_badge_number', 'users', ['badge_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_badge_number', 'users', type_='unique')
    op.drop_column('users', 'status')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'badge_number')
    op.drop_column('users', 'office_building')
    op.drop_column('users', 'job_title')
    op.drop_constraint('fk_unknown_faces_camera_id', 'unknown_faces', type_='foreignkey')
    op.drop_index(op.f('ix_unknown_faces_unknown_person_id'), table_name='unknown_faces')
    op.drop_column('unknown_faces', 'camera_id')
    op.drop_column('unknown_faces', 'unknown_person_id')
    op.drop_constraint('fk_recognition_logs_camera_id', 'recognition_logs', type_='foreignkey')
    op.drop_column('recognition_logs', 'camera_id')
    op.drop_index(op.f('ix_watchlist_entries_watchlist_id'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_user_id'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_unknown_face_id'), table_name='watchlist_entries')
    op.drop_index(op.f('ix_watchlist_entries_id'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index(op.f('ix_face_embeddings_user_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_unknown_face_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_access_history_visitor_id'), table_name='access_history')
    op.drop_index(op.f('ix_access_history_user_id'), table_name='access_history')
    op.drop_index(op.f('ix_access_history_unknown_face_id'), table_name='access_history')
    op.drop_index(op.f('ix_access_history_timestamp'), table_name='access_history')
    op.drop_index(op.f('ix_access_history_id'), table_name='access_history')
    op.drop_table('access_history')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_camera_locations_id'), table_name='camera_locations')
    op.drop_table('camera_locations')
    # ### end Alembic commands ###
