"""index recognition_logs.user_id

Revision ID: 6c946c8f3423
Revises: 09dfff37227f
Create Date: 2026-07-24 01:21:17.129565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c946c8f3423'
down_revision: Union[str, Sequence[str], None] = '09dfff37227f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recognition_logs_user_id'), 'recognition_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_logs_user_id'), table_name='recognition_logs')
    # ### end Alembic commands ###
